#!/usr/bin/env bash

# change following to your target distributions
declare -a DIST=(
  darwin/amd64
  darwin/arm64
  linux/amd64
  linux/arm64
  windows/amd64
  windows/arm64
)

# only safe way to remove specific dist dir
distdir="$(dirname "$(realpath "$0")")/dist"
rm -rf "$distdir" 2>/dev/null
mkdir "$distdir" 2>/dev/null

for dist in "${DIST[@]}"; do
  export GOOS=${dist%/*}
  export GOARCH=${dist#*/}
  name="kubectl-plugin_${GOOS}_${GOARCH}"
  [[ "$GOOS" == windows ]] && name="${name}.exe"
  echo "Building $name ..."
  go build -o "dist/$name"
done
echo done.
