name: Build and Release
on:
  create:
    tags:
      - v*

jobs:
  build:
    name: Build with latest Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go

      - name: Check out code
        uses: actions/checkout@v1

			- name: Build it
         run: go build -v ./...

  release:
    needs: [build]
    name: Release on GitHub
    steps:
      - name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

      - name: Create release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
